title: jekylllll
markdown: kramdown
exclude: ["Rakefile", "Gemfile", "Gemfile.lock"]
description: jekyllllljekylllll

kramdown:
  #use_coderay: true
  #enable_coderay: true
  #coderay_line_numbers: table
  input: GFM
  #syntax_highlighter: rouge
