title: jekylllll
markdown: redcarpet
syntax_highlighter: coderay
exclude: ["Rakefile", "Gemfile", "Gemfile.lock"]
description: jekyllllljekylllll

redcarpet:
  use_coderay: true
  enable_coderay: true
  coderay_line_numbers: table
  input: GFM
